steps:
  # Step 1: Install dependencies
  - name: "node"
    entrypoint: "npm"
    args: ["install"]

  # Step 2: Run tests
  - name: "node"
    entrypoint: "npm"
    args: ["test"]

options:
  logging: CLOUD_LOGGING_ONLY
